# Generated by Django 5.0.1 on 2025-12-01 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevent',
            name='send_notification',
            field=models.BooleanField(default=False, help_text='Send push notification before event starts'),
        ),
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_events_enabled', models.BooleanField(default=True, help_text='Enable notifications for agenda events')),
                ('agenda_reminder_minutes', models.IntegerField(default=15, help_text='Minutes before event to send notification')),
                ('shopping_updates_enabled', models.BooleanField(default=False, help_text='Enable notifications for shopping list updates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Preferences',
                'verbose_name_plural': 'User Notification Preferences',
            },
        ),
    ]
