# Generated by Django 5.0.1 on 2025-12-01 00:28

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The memory content (what happened, what was said, etc.)')),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, help_text='Vector embedding for semantic search', null=True)),
                ('memory_type', models.CharField(choices=[('shopping', 'Shopping'), ('agenda', 'Agenda'), ('preference', 'Preference'), ('fact', 'Fact'), ('interaction', 'Interaction'), ('other', 'Other')], default='interaction', help_text='Type of memory', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (e.g., item names, dates, etc.)')),
                ('importance', models.FloatField(default=0.5, help_text='Importance score (0.0 to 1.0) for filtering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'memory_type'], name='assistant_m_user_id_1bb9ef_idx'), models.Index(fields=['user', 'created_at'], name='assistant_m_user_id_8456a2_idx')],
            },
        ),
    ]
