# Generated by Django 5.0.1 on 2025-12-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='notes_enabled',
            field=models.BooleanField(default=True, help_text='Enable notifications for notes'),
        ),
    ]
