# Generated by Django 5.0.1 on 2025-12-08 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_conversation_conversationmessage_terminalapiconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(help_text='Home Assistant entity ID (e.g., climate.kitchen)', max_length=255)),
                ('alias', models.CharField(help_text="Friendly name (e.g., 'ar condicionado da cozinha')", max_length=200)),
                ('area', models.CharField(blank=True, help_text="Area/room name (e.g., 'Cozinha')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'area'], name='assistant_d_user_id_01fee0_idx'), models.Index(fields=['user', 'entity_id'], name='assistant_d_user_id_6b8743_idx')],
                'unique_together': {('user', 'entity_id')},
            },
        ),
    ]
