# Generated by Django 5.0.1 on 2026-01-25 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_videotranscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videotranscription',
            new_name='assistant_v_user_id_ead4ce_idx',
            old_name='assistant_vt_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='videotranscription',
            new_name='assistant_v_user_id_5f46e6_idx',
            old_name='assistant_vt_user_updated_idx',
        ),
    ]
